freebsd/drm-kmod

- Makefile
On powerpc64, MACHINE_CPUARCH is powerpc, but we check for powerpc64.
> Fix build on powerpc64

- drivers/gpu/drm/amd/amdgpu/psp_v11_0.c
- drivers/gpu/drm/amd/display/dc/dcn20/dcn20_resource.c
These are the changes that are needed to get the drm driver working with a Navi10 card on FreeBSD. They consist of
1. Increase mdelay in SOS loading (from 20 to 200).
2. Wrap some floating point operations with `kernel_fpu_begin/end` pairs.
I would say the first change probably needs consideration. I did not spend time to find out how much the mdelay should increase. The only error the `psp_wait_for()` function can return is that it timed out. So, I just started with a large number and didn't look at reducing it. It might be better to get the the pull request in and the card working before looking at reducing this time afterwards.
Anyway, with these changes and the mesa_devel package, X11 works. Haven't tried Wayland.
> Get Navi10 card working on FreeBSD

- drivers/gpu/drm/amd/display/dc/dcn20/dcn20_resource.c
Later changes -CURRENT seems to have revealed more unprotected FPU access.
It seems that this validate bandwith may have some extra FPU use, so
add additional calls to fpu_begin and fpu_end.
> Add some more FPU protections

- drivers/gpu/drm/amd/amdgpu/amdgpu.h
- drivers/gpu/drm/amd/amdgpu/amdgpu_ucode.h
- drivers/gpu/drm/radeon/radeon.h
- linuxkpi/gplv2/include/linux/dma-fence.h
Remove multiple duplicate linux_fimrware related changes inside drivers which linux/firmware.h already handles.
Also use a more portable (official) macro name within the implementation to allow for portability.
> linuxkpi cleanup

- drivers/dma-buf/dma-resv.c
LinuxKPI in base have ksize() implemented since r364964.
> Remove #ifdef __linux__ from dma-resv.c

- drivers/gpu/drm/drm_prime.c
Fixes https://github.com/FreeBSDDesktop/kms-drm/issues/248 (damn why do we still have two repositories >_<)
note: I first wanted to do this in `linux_ioctl.c` in the linuxulator itself, but there we get the ioctl data *before* copying it from userspace, so that would mean copyin-fix-copyout which is awful.
testing: `/compat/linux/bin/strace /compat/linux/bin/glxgears` without any dri3 disabling variables (might also need to rebuild and reload `linsysfs` with https://reviews.freebsd.org/D26836 applied especially on amdgpu) — should be rendering in hardware, `DRM_IOCTL_PRIME_HANDLE_TO_FD` should be present without errors in the syscall trace
> drm_prime_handle_to_fd_ioctl: translate O_ flags for Linuxulator

- drivers/gpu/drm/drm_internal.h
- drivers/gpu/drm/drm_ioctl.c
- drivers/gpu/drm/drm_pci.c
- include/uapi/drm/drm.h
This API is used in libdrm for OpenBSD and DragonFly.
Adopting this API would allow making libdrm code simpler, as well as improve support for GPU usage in Capsicum capability mode (no need to do anything about hw.dri sysctls anymore).
ref: https://gitweb.dragonflybsd.org/dragonfly.git/commitdiff/8a697a22391bbafe215fab92a6cb29ed3a1f6edf
example libdrm patch (keeping backwards compatibility): https://github.com/DankBSD/ports/commit/85482d713db35679e03f55551fc000f33461739e
> [5.4-lts] implement DRM_IOCTL_GET_PCIINFO, matching OpenBSD and DragonFly

- drivers/gpu/drm/i915/display/intel_display.c
- drivers/gpu/drm/i915/display/intel_frontbuffer.c
- drivers/gpu/drm/i915/display/intel_frontbuffer.h
- drivers/gpu/drm/i915/display/intel_overlay.c
- drivers/gpu/drm/i915/gem/i915_gem_clflush.c
- drivers/gpu/drm/i915/gem/i915_gem_domain.c
- drivers/gpu/drm/i915/gem/i915_gem_object.c
- drivers/gpu/drm/i915/gem/i915_gem_object.h
- drivers/gpu/drm/i915/gem/i915_gem_object_types.h
- drivers/gpu/drm/i915/i915_gem.c
- drivers/gpu/drm/i915/i915_vma.c
Manually applied backport of e85ade1f50aae464ce196672faa7a099fd1721ed
by Chris Wilson <chris@chris-wilson.co.uk>.  Original commit msg:
Since obj->frontbuffer is no longer protected by the struct_mutex, as we
are processing the execbuf, it may be removed. Mark the
intel_frontbuffer as rcu protected, and so acquire a reference to
the struct as we track activity upon it.
Closes: https://gitlab.freedesktop.org/drm/intel/issues/827
Fixes: 8e7cb1799b4f ("drm/i915: Extract intel_frontbuffer active tracking")
Signed-off-by: Chris Wilson <chris@chris-wilson.co.uk>
Cc: Matthew Auld <matthew.auld@intel.com>
Cc: <stable@vger.kernel.org> # v5.4+
Reviewed-by: Joonas Lahtinen <joonas.lahtinen@linux.intel.com>
Link: https://patchwork.freedesktop.org/patch/msgid/20191218104043.3539458-1-chris@chris-wilson …
> drm/i915: Hold reference to intel_frontbuffer as we track activity

- drivers/gpu/drm/i915/display/intel_display.c
- drivers/gpu/drm/i915/i915_drv.h
- linuxkpi/gplv2/include/asm/processor.h
with spinlock or critical section held" assertion on Intel Kaby Lake GPU
(Issue #9) with replacment of work_struct with its critical section-friendly
variant called irq_work.
The panic message is:
panic: acquiring blockable sleep lock with spinlock or critical section held (sleep mutex) linux_wq_exec @ /usr/src/sys/compat/linuxkpi/common/src/linux_work.c:105
cpuid = 3
time = 1617926020
KDB: stack backtrace:
db_trace_self_wrapper() at db_trace_self_wrapper+0x2b/frame 0xfffffe00da4e6010
vpanic() at vpanic+0x181/frame 0xfffffe00da4e6060
panic() at panic+0x43/frame 0xfffffe00da4e60c0
witness_checkorder() at witness_checkorder+0xf3e/frame 0xfffffe00da4e6280
__mtx_lock_flags() at __mtx_lock_flags+0x94/frame 0xfffffe00da4e62d0
linux_queue_work_on() at linux_queue_work_on+0x9a/frame …
> Fix another one instance of "acquiring blockable sleep lock

- drivers/gpu/drm/linux_fb.c
- drm/Makefile
AMD drivers use the remove_conflicting_pci_framebuffers function to kick the EFI framebuffer out early, to prevent it from messing with VRAM, corrupting things used by the driver loading process.
Our implementation could not actually remove native vt drivers, only LinuxKPI registered ones.
This commit solves the amdgpu/radeon efifb conflict, i.e. fixes #60
---
<details>
<summary>example dmesg log</summary>
```
[4] <6>[drm] amdgpu kernel modesetting enabled.
[4] drmn0: <drmn> on vgapci0
[4] VT: Replacing driver "efifb" with new "dummy".
[4] vgapci0: child drmn0 requested pci_enable_io
[4] vgapci0: child drmn0 requested pci_enable_io
[4] sysctl_warn_reuse: can't re-use a leaf (hw.dri.debug)!
[4] <6>[drm] initializing kernel modesetting (VEGA10 0x1002:0x687F 0x1002:0x6B76 0xC1).
[4] <6>[drm] …
```
> Switch to dummy vt backend in __remove_conflicting when needed

- linuxkpi/gplv2/include/linux/cpu.h
- linuxkpi/gplv2/include/linux/stringify.h
Update checks for __FreeBSD_version[1] after MFCs to stable/13 were done. (#95)
[1] ((__FreeBSD_version < 1400000) && (__FreeBSD_version >= 1300512))
Co-authored-by: Bjoern A. Zeeb <bz@FreeBSD.org>
> cherry-pick of "Update checks for __FreeBSD_version[1] after MFCs to stable/13 were done"

- drivers/gpu/drm/amd/display/dc/dcn20/dcn20_resource.c
- drivers/gpu/drm/amd/display/dc/dcn21/dcn21_resource.c
And remove the last leftovers of our local `ifdef`'d FPU blocks that are now duplicates.
> [5.6-wip] Backport FPU fixes

- drivers/gpu/drm/amd/display/dc/dcn20/dcn20_resource.c
- drivers/gpu/drm/amd/display/dc/dcn21/dcn21_resource.c
This should fix #101 on 5.5-stable hopefully?
Since https://reviews.freebsd.org/D29921 our FPU sections are critical sections (`NOCTX`) as they are on Linux, and our `INVARIANTS` caught the waiting-malloc-under-critical-section issue that was only found by the Linux developers *several* releases later. (dcn20 in 5.9, and then dcn21 in 5.12 — actually dcn21 has just been [left *without* an FPU block (!) until then](https://github.com/torvalds/linux/commit/41401ac67791810dd880345962339aa1bedd3c0d))
ARGH WHY IS LINUX SO SLOPPY WITH THE FPU STUFF
> [5.5-stable] Fix malloc-in-FPU-section

- drivers/dma-buf/dma-buf.c
The following commit removed thread argument from fo_stat.
https://cgit.freebsd.org/src/commit/?id=2b68eb8e1dbbdaf6a0df1c83b26f5403ca52d4c3
This fix is required for graphics/drm-{current,devel}-kmod.
> Fix build after 1400037

- Makefile
- amd/Makefile
- drivers/gpu/drm/linux_fb.c
- kconfig.mk
- linuxkpi/gplv2/include/asm/set_memory.h
- linuxkpi/gplv2/include/linux/io.h
- linuxkpi/gplv2/include/linux/irq.h
No clue if it actually works as I have yet to plug a GPU into my Unmatched board, but this gets it building.
NB: Depends on D31996 and D31999
> Add RISC-V support and fix powerpc64 detection

- drivers/gpu/drm/i915/display/intel_display.c
- drivers/gpu/drm/i915/i915_drv.h
Test conducted shows that we can skip scheduling of free_work in critical section as intel_atomic_helper_free_state() will be called very soon from another safe code path.
Reported by @evadot via gitter.im
> Attempt to fix 3da42da6111 breaking suspend/resume on whiskeylake

- drivers/dma-buf/dma-fence.c
- drivers/dma-buf/dma-resv.c
- drivers/gpu/drm/i915/display/intel_display.c
- drivers/gpu/drm/i915/gem/i915_gem_busy.c
- drivers/gpu/drm/i915/i915_active.c
- drivers/gpu/drm/i915/i915_active_types.h
- drivers/gpu/drm/i915/i915_scheduler.c
- linuxkpi/gplv2/include/linux/dma-resv.h
as some callbacks called through dma_fence_is_signaled use various
blockable calls triggering kernel assertions. Instead of it use rwlock
to block seqlock readers if dma_resv_add_shared_fence is preempted.
Revert some hacks drm-kmod uses to workaround the assertions.
> dma-buf: Do not disable preemption in dma_resv_add_shared_fence

- drivers/gpu/drm/i915/gt/intel_gt.c
- i915/Makefile
For !DEBUGFS case, the module would fail to load with:
```
link_elf_obj: symbol debugfs_create_dir undefined
linker_load_file: /boot/kernel/i915kms.ko - unsupported file type
```
This change removes the debugfs dependencies from `i915/gt/*`.
> i915: Fix build with !DEBUGFS case.

- drivers/dma-buf/dma-buf.c
Some programs ([waypipe](https://gitlab.freedesktop.org/mstoeckl/waypipe/-/blob/15aab5c344636336f5327d91d3e6a92733503312/src/util.c#L205-214)) use poll to check inherited file descriptors, and some other programs (terminal emulators?) can have non-CLOEXEC dmabufs that leak into waypipe, causing a panic.
Pointy hat: ngor
> [master] do not panic on dma_buf_poll

- linuxkpi/bsd/include/linux/pm.h
add #include_next to pm.h to also have access to the in-tree file.
This will be necessary in main and stable/13 in order to migrate
pm_message_t from kernel.h to pm.h.
Sponsored by:	The FreeBSD Foundation
> LinuxKPI BSD: add include_next to pm.h

- linuxkpi/bsd/include/asm/processor.h
- linuxkpi/gplv2/src/linux_compat.c
One change add a missing include (not sure entirely why it is needed in this case but compiler complained, compiler wins ;-)
The other change removes superfluous includes discovered during https://github.com/freebsd/drm-kmod/pull/169
> Cleanup some includes

- drivers/gpu/drm/amd/display/dc/clk_mgr/dcn30/dcn30_clk_mgr.c
- drivers/gpu/drm/amd/display/dc/core/dc.c
- drivers/gpu/drm/amd/display/dc/dcn30/dcn30_resource.c
This fixes crash/freeze on load on "RDNA2" GPUs \o/
(bizzare thing during debugging: it all looked like a GPU crash / system freeze.. until I disabled PSP memory training (because the memory training line was the last print before the screen turning off) and then I started seeing FPU panics)
> Backport FPU fixes for DCN3.x (Big Navi - sienna_cichlid/navy_flounder)

- drivers/gpu/drm/amd/display/dc/os_types.h
- kconfig.mk
Related to https://github.com/freebsd/drm-kmod/issues/176.
> Fix powerpc64* and riscsv64* defines

- drivers/gpu/drm/i915/intel_uncore.h
- linuxkpi/bsd/include/asm/processor.h
- linuxkpi/bsd/include/linux/io-64-nonatomic-lo-hi.h
Add missing sys/systm.h include and non-atomic versions of readq() and writeq() for __FreeBSD_version < 1400067.
> linuxkpi: Fix build on i386

- linuxkpi/bsd/include/linux/dma-mapping.h
- linuxkpi/bsd/include/linux/io.h
- linuxkpi/bsd/include/linux/kernel.h
- linuxkpi/bsd/include/linux/mm.h
- linuxkpi/bsd/include/linux/pm.h
- linuxkpi/bsd/include/linux/refcount.h
- linuxkpi/gplv2/include/linux/compiler.h
- linuxkpi/gplv2/include/linux/pagevec.h
- linuxkpi/gplv2/include/linux/pci.h
This fixes drm-kmod's build on FreeBSD 13-STABLE before the recent merges in base and the corresponding version bump to 1301507.
> linuxkpi: Fix commit "Chase base linuxkpi MFC"'s 13-STABLE version

- drivers/gpu/drm/drm_sysctl_freebsd.c
In commit freebsd/freebsd-src@d3f96f661050e9bd21fe29931992a8b9e67ff189, the structure was changed from a linked list to a red-black tree.
`__FreeBSD_version` was bumped to 1400071 in the process.
> drm_sysctl_freebsd.c: Adapt loop over `SYSCTL_CHILDREN()` to FreeBSD 1400071+

- linuxkpi/bsd/include/linux/dma-mapping.h
dma_map_sgtable internally uses the dma_map_sg_attrs helper. The problem is that dma_map_sg_attrs returns the number of entries mapped, whereas dma_map_sgtable returns nonzero on failure.  This leads to dma_map_sgtable returning non-zero-but-positive values which tricks other areas of the stack into thinking nents is a valid pointer.
This checks if nents is valid and returns zero if so, updating the nents field in sgt. This fixes PRIME render offload with nvidia-drm.
This review handles installs before FreeBSD version 1400066, where dma_map_sgtable comes from drm-kmod instead of from base.
Related: https://reviews.freebsd.org/D37611
> linuxkpi: Fix return value of dma_map_sgtable

- scripts/drmpatch
It is useful when the script runs in an unattended terminal window. If the terminal and the window manager/desktop environment are configured for it, the bell will trigger the "urgent hint" for the terminal window. For instance with Sway and Waybar, the workspace number/name in bar will be red, likewise for the terminal window title and borders.
This way, we can run the script, forget about it and do something else. When the script exits, for instance because it failed to apply a patch, we are notified.
> scripts/drmpatch: Ring the terminal bell when the script exits

- drivers/gpu/drm/i915/gem/i915_gem_shmem.c
This function will be exposed by linuxkpi shortly.
See https://reviews.freebsd.org/D38531.
> i915: Remove `totalram_pages()` function

- drivers/dma-buf/dma-resv.c
The function is called in between `rcu_read_lock()`/`rcu_read_unlock()`. Dropping this lock to wait for the writer thread to finish on FreeBSD was lost in the code refactoring.
> dma-buf: Call rcu_read_unlock() before locking `cursor->obj->rw`

- amd/amdgpu/Makefile
- dmabuf/Makefile
- drm/Makefile
- i915/Makefile
- linuxkpi_version.mk
- radeon/Makefile
- ttm/Makefile
One of this issues with running nvidia-drm against drm-kmod's master branch is that there are some mismatches in compatibility that require the `LINUXKPI_VERSION` macro to be defined. Here is an example of a build breaking due to nvidia-drm not having that defined:
https://cirrus-ci.com/task/4762004506804224
Currently I added `-DLINUXKPI_VERSION=51600` to nvidia-drm to get builds against master working, but we need a better solution long term. nvidia-drm needs a way to get this directly from drm-kmod, since it may be different between master, `5.15-lts`, `5.10-lts`, etc.
I took a stab at a solution and came up with this: a new `linuxkpi_version.mk` makefile that nvidia-drm can include to get the proper version defined and added to its `CFLAGS`. I tested that both nvidia-drm and drm-kmod …
> Add linuxkpi_version.mk for cross-project version tracking

- amd/amdgpu/Makefile
- amd/amdkfd/Makefile
- drm/Makefile
- dummygfx/Makefile
- i915/Makefile
- radeon/Makefile
- ttm/Makefile
This file does not exist and is not used anywhere, and depending on it causes `WITH_META_MODE` to never do the fast incremental build.
```
drm-kmod❯ ls -la  /usr/home/val/os/target/base-obj/usr/home/val/os/base/amd64.amd64/sys/GENERIC/ | rg opt_c
-rw-r--r--  1 val  val          0 May  5 06:20 opt_callout_profiling.h
-rw-r--r--  1 val  val          0 May  5 06:20 opt_cam.h
-rw-r--r--  1 val  val         49 May  5 06:20 opt_capsicum.h
-rw-r--r--  1 val  val          0 May  5 06:20 opt_carp.h
-rw-r--r--  1 val  val          0 May  5 06:20 opt_cc.h
-rw-r--r--  1 val  val          0 May  5 06:20 opt_cd.h
-rw-r--r--  1 val  val          0 May  5 06:20 opt_cfi.h
-rw-r--r--  1 val  val          0 May  5 06:20 opt_clock.h
-rw-r--r--  1 val  val         30 May  5 06:20 opt_config.h
-rw-r--r--  1 …
```
> Remove dep on nonexistent opt_compat.h

- drivers/gpu/drm/amd/amdgpu/amdgpu_device.c
- drivers/gpu/drm/amd/amdgpu/amdgpu_fb.c
- drivers/gpu/drm/drm_fb_helper.c
- drivers/gpu/drm/drm_modeset_lock.c
- drivers/gpu/drm/drm_os_freebsd.c
- drivers/gpu/drm/drm_os_freebsd.h
- drivers/gpu/drm/i915/display/intel_fbdev.c
- drivers/gpu/drm/i915/gem/i915_gem_stolen.c
- drivers/gpu/drm/i915/i915_module.c
- drivers/gpu/drm/i915/i915_pci.c
- drivers/gpu/drm/i915/intel_freebsd.c
- drivers/gpu/drm/linux_fb.c
- drivers/gpu/drm/radeon/radeon_fb.c
- drivers/gpu/drm/vt_drmfb.c
- drivers/gpu/drm/vt_drmfb.h
- drm/Makefile
- include/drm/drm_fb_helper.h
- linuxkpi/bsd/include/uapi/linux/fb.h
- linuxkpi/gplv2/include/linux/fb.h
This patch series replaces our current vt(4) integration layer with a new one relying entirely on `drm_fb_helper.c`.
In Linux 5.17, the amdgpu driver relies entirely on `drm_fb_helper` to handle its framebuffer. Indeed, the framebuffer-specific code is removed.
Also in Linux 5.17, something changed in the i915 driver. I don't know exactly what, but the memory region passed to vt(4) and `vt_fb` isn't the one displayed on the screen. Therefore, all writes made by `vt_fb` leads to no changes on the screen and the computer looks frozen (that's not the case). However, when I vt-switch to another tty, the screen is refreshed to show the content of the tty active *before* the switch. Switching tty is the only time `vt_fb` calls into DRM. There is enough evidence that the i915 driver now assumes …
> Use `drm_fb_helper`'s emulation of Linux `fbdev` to integrate with FreeBSD's vt(4)

- scripts/drmcheckapplied
- scripts/extract-commit-title-from-patch.awk
Sometimes, a commit subject is used by several commits, so this property alone is not enough to discriminate already applied patches.
By using the commit date in addition to the subject, we are sure the combination is unique.
> drmcheckapplied: Use author date to reduce false positives

- drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm_trace_freebsd.h
- drivers/gpu/drm/i915/i915_trace.h
Around various optional KTR macro CTR calls unused variables were used. Initialise the variable, use the local variable (otherwise set but not used) rather than the one passed in.
Also __func__ is not a string literal which can be concatenated to a string, so use %s in the format string and (if needed) split up the CTR call into two calls.
Sponsored by:	The FreeBSD Foundation (MFC wifi bits w/o breaking the build)
> drm-kmod 5.15-lts: make LINT kernels compile

- amd/amdgpu/Makefile
This is a workaround to deal with the ctfmerge(1) utility segfaulting after the update to drm 6.6. See the FreeBSD bug report:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276828
This is reproducible in my environment, but I have no idea if others are affected.
> amdgpu: disable CTF

- amd/amdkfd/Makefile
amdkfd is commented out in amd/Makefile.  Remove the include in case it is ever reconnected to the build.
Fixes: 5b2279ae2a59 ("Remove ${.CURDIR}-relative linuxkpi include")
> Remove one more ${.CURDIR}-relative linuxkpi include

- drm/Makefile
- dummygfx/Makefile
- ttm/Makefile
Dummy directories do not exist in the repo so the build was failing with clang 19's stricter include path warnings + Werror. These lines were already removed from a bunch of directories but somehow not from drm/ttm..
Fixes: 5b2279ae2a59 ("Remove ${.CURDIR}-relative linuxkpi include")
---
applies to 6.1-lts exactly as well
> Remove remaining ${.CURDIR}-relative dummy includes

- scripts/update-firmwares.sh
... and update `drm-kmod-firmware`
It greps the firmware filenames from the amdgpu, i915 and radeon drivers, copy the files from the linux-firmware repository to the drm-kmod-firmware one, and finally call the `gen-makefiles` scrips in `drm-kmod-firmware`.
It can be called like this:
scripts/update-firmwares.sh \
/path/to/linux-firmware \
/path/to/drm-kmod-firmware
It doesn’t update the `{amdgpu,i915,radeon}kmsfw/Makefile` to add new subdirectories.
> scripts/update-firmwares.sh: New script to extract firmware names

- amd/amdgpu/Makefile
- amd/amdkfd/Makefile
- dmabuf/Makefile
- drm/Makefile
- dummygfx/Makefile
- i915/Makefile
- radeon/Makefile
- ttm/Makefile
We currently rely on the kernel linker's misbehaviour of exporting local symbols from modules, controlled by the debug.link_elf_obj_leak_locals and debug.link_elf_leak_locals sysctls.
Explicitly export all symbols (making the current behaviour explicit) as a step to turning off the sysctls by default.  A future change should have us export only the desired symbols.
Sponsored by:	The FreeBSD Foundation
> drm-kmod: Export all symbols

- drivers/gpu/drm/i915/gem/i915_gem_mman.c
vm_page_next() is removed in 15.0.
This affects most of the DRM branches. Should I submit PRs for all of them?
> i915: Use iterators to traverse resident VM object pages

- drivers/dma-buf/dma-fence.c
After jiffies was widened, MAX_SCHEDULE_TIMEOUT gets truncated to 0xffffffff, which is sign-extended to a negative value.
> dma-buf: Fix the type of the return variable in dma_fence_wait_timeout()

- drivers/gpu/drm/drm_auth.c
Fix incomplete check for the current master of the device, which breaks modesetting_drv when switching to VT and back to X.
This should be also cherry-picked to older drm code (drm-61, drm-515 and drm-510)
Fixes #175
> drm: check if fpriv is the current master of the device

- drivers/dma-buf/dma-buf.c
FreeBSD does not NULL-check most of the fields of struct fileops. For example, calling fchmod on a dmabuf fd would make the kernel panic due to a NULL pointer dereference.
The correct way to leave some operations unimplemented is to fill the struct with the appropriate invfo_* stubs.
> Fill all fileops with valid pointers

- drivers/gpu/drm/drm_pci.c
- drivers/gpu/drm/drm_sysctl_freebsd.c
LinuxKPI seems to provide everything needed here, which allows us to remove the special casing for FreeBSD.
Switch from bsddev and FreeBSD native functions to LinuxKPI variables and functions/macros; this will avoid conflicts with upcoming additions to LinuxKPI.
Sponsored by:	The FreeBSD Foundation
> drm: use LinuxKPI PCI functions rather than bsd native [6.1-lts]

- drivers/gpu/drm/i915/display/intel_crtc.c
- drivers/gpu/drm/i915/display/intel_vblank.c
Use preempt_en/disable where upstream calls local_irq_en/disable in intel_pipe_update_start, intel_pipe_update_end, and intel_vblank_evade as already done elsewhere in drm/i915.  There are additional cases that need investigation but this is now usable on my 11th gen Intel laptop.
Closes: #375
> drm/i915: Additional local_irq_en/disable conversions

- drivers/gpu/drm/amd/display/dc/dml/calcs/dce_calcs.c
'struct bw_calcs_data' is just a temporary big structure that does not need physically contiguous memory, so just do a regular allocation.
This fixes noticeable slowdowns on FreeBSD by removing a contiguous allocation in hot paths.
Backport of #377.
Sponsored by:   The FreeBSD Foundation
> Backport of "dce_calcs: Avoid ~14kB contiguous allocation" for 6.1

- drivers/gpu/drm/amd/display/dc/calcs/dce_calcs.c
'struct bw_calcs_data' is just a temporary big structure that does not need physically contiguous memory, so just do a regular allocation.
This fixes noticeable slowdowns on FreeBSD by removing a contiguous allocation in hot paths.
Backport of #377.
Sponsored by:   The FreeBSD Foundation
> Backport of "dce_calcs: Avoid ~14kB contiguous allocation" for 5.10
